name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - uses: actions/upload-artifact@v2
        with:
          name: demoservice-0.0.1-SNAPSHOT.jar
          path: target/
      - name: Build container image
        uses: docker/build-push-action@v1
        with:
         username: ${{github.actor}}
         password: ${{secrets.GITHUB_TOKEN}}
         registry: docker.pkg.github.com
         repository: archnaaju/Sample-Maven-Workflow/demoservice
         tag_with_sha: true
